format = """
$directory\
$username\
$hostname\
$time\
$git_branch\
$git_state\
$php\
$golang\
"""

[php]
format = '[$symbol]($style)'
symbol = 'ğŸ˜php '

[golang]
format = '[$symbol]($style)'
symbol = 'ğŸ¹go '
